### ISSUE TITLE
Bug when rendering 🎛, 🎟 or 🎫 glyphs from Noto-COLRv1.ttf

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/black-renderer#116]
`blackrenderer Noto-COLRv1.ttf  🎛    test.png`

```
Traceback (most recent call last):
  File "/Users/just/code/git/BlackFoundry/black-renderer/venv/bin/blackrenderer", line 33, in <module>
    sys.exit(load_entry_point('blackrenderer', 'console_scripts', 'blackrenderer')())
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/__main__.py", line 43, in main
    renderText(
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/render.py", line 78, in renderText
    font.drawGlyph(glyph.name, canvas, palette=palette)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 166, in drawGlyph
    self._drawGlyphCOLRv1(glyph, canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 191, in _drawGlyphCOLRv1
    self._drawPaint(glyph.Paint, canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 211, in _drawPaint
    drawHandler(paint, canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 219, in _drawPaintColrLayers
    self._drawPaint(self.colrLayersV1.Paint[i], canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 211, in _drawPaint
    drawHandler(paint, canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 353, in _drawPaintComposite
    self._drawPaint(paint.BackdropPaint, canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 211, in _drawPaint
    drawHandler(paint, canvas)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/font.py", line 223, in _drawPaintSolid
    canvas.drawPathSolid(self.currentPath, color)
  File "/Users/just/code/git/BlackFoundry/black-renderer/Lib/blackrenderer/backends/skia.py", line 104, in drawPathSolid
    self.canvas.drawPath(path.path, paint)
AttributeError: 'NoneType' object has no attribute 'path'
```

Reported for FontGoggles: https://github.com/justvanrossum/fontgoggles/issues/278

https://github.com/googlefonts/noto-emoji/blob/main/fonts/Noto-COLRv1.ttf

**Comment by punchcutter** [comment]
I'm not sure what BMP has to do with it, but I get a failure on these three: 🎛 🎟 🎫

**Comment by justvanrossum** [comment]
Yeah, I blindly took that from the original report. Thanks!

**Comment by justvanrossum** [comment]
I think the problem is in a `PaintComposite` Paint, where the `BackdropPaint` is just a color, without a shape being drawn at all. This is an oversight in the blackrenderer implementation, and fixing it may be a bit harder that one would hope, esp. with all backends.

```xml
      <Paint index="48" Format="32"><!-- PaintComposite -->
        <SourcePaint Format="1"><!-- PaintColrLayers -->
          <NumLayers value="11"/>
          <FirstLayerIndex value="0"/>
        </SourcePaint>
        <CompositeMode value="src_in"/>
        <BackdropPaint Format="2"><!-- PaintSolid -->
          <PaletteIndex value="0"/>
          <Alpha value="0.7"/>
        </BackdropPaint>
      </Paint>
```

**Comment by punchcutter** [comment]
I was about to write the same thing. I checked that all those glyphs have PaintComposite and I looked for other glyphs using PaintComposite and they also fail.

**Comment by anthrotype** [comment]
hey! yes, nanoemoji uses that trick to encode SVG group-level opacity, when you set `opacity` attribute on a `<g>` element containing several paths (for it's not the same thing as setting opacity to each individual paths as you may imagine).
https://github.com/googlefonts/nanoemoji/blob/2ffdd23faad153c5cec763b6e210befc9d704cd1/src/nanoemoji/color_glyph.py#L334-L338

**Comment by justvanrossum** [comment]
I was recently thinking about "how would that work in COLRv1" and going "Hm, maybe with a solid color as a backdrop backdrop", and now I'm in deep trouble with blackrenderer... Ideally I'd locate @drott's Skia code that implements this.

**Comment by justvanrossum** [comment]
(Note to self) see the "bounded" notes in this section of the spec: https://learn.microsoft.com/en-us/typography/opentype/spec/colr#format-32-paintcomposite

**Comment by anthrotype** [comment]
fwiw, this particular font (and all those made with nanoemoji compiler) has explicit ClipBoxes for all the color glyphs, which should make the bounded-ness easier to determine

**Comment by yarmola** [comment]
> see the "bounded" notes in this section of the spec

Interesting that it is exactly the same problem that I have in FL COLRv1 parser: I tried to use FontGoggles to preview glyph with which I had problem and found the crash, incorrectly attributing it to unicode.

**Comment by anthrotype** [comment]
correct. the soft-light gives the waved region flags a more tridimensional appearance, that's done in https://github.com/googlefonts/noto-emoji/blob/f826707b28355f6cd1593f504427ca2b1f6c4c19/colrv1_add_soft_light_to_flags.py#L158-L166
